# Generated by Django 4.2.16 on 2024-11-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('contacts', models.TextField()),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('pics', models.FileField(upload_to='projects/')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReplyField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('request_box', models.TextField(help_text='Максимальное количество: 500 символов', max_length=500)),
                ('email', models.EmailField(help_text='Укажите адрес своего e-mail', max_length=254)),
                ('phone', models.CharField(help_text='Укажите номер телефона для связи', max_length=50)),
            ],
        ),
    ]
