# Generated by Django 4.2.16 on 2024-11-14 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj_site_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pics',
        ),
        migrations.AlterField(
            model_name='menu',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='dj_site_app/background/'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dj_site_app/projects/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dj_site_app.project')),
            ],
        ),
    ]
