# Generated by Django 4.2.16 on 2024-11-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_site_app', '0003_project_image_alter_menu_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='dj_site_app/static/dj_site_app/backgrounds'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='dj_site_app/media/'),
        ),
    ]
