# Generated by Django 4.2.16 on 2024-11-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_site_app', '0004_alter_menu_background_image_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('contacts', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
