# Generated by Django 4.2.16 on 2024-11-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_site_app', '0006_remove_project_image_projectimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='contacts',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='order',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='replyfield',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='replyfield',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='replyfield',
            name='request_box',
            field=models.TextField(max_length=500),
        ),
    ]
