# Generated by Django 4.2.16 on 2024-11-28 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dj_site_app', '0007_remove_about_contacts_alter_project_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'ОБО МНЕ', 'verbose_name_plural': 'ОБО МНЕ'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'ПРОЕКТ', 'verbose_name_plural': 'ПРОЕКТЫ'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['order'], 'verbose_name': 'Изображение и проект', 'verbose_name_plural': 'Все изображения'},
        ),
        migrations.AlterModelOptions(
            name='replyfield',
            options={'verbose_name': 'КОНТАКТ', 'verbose_name_plural': 'КОНТАКТЫ'},
        ),
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.TextField(verbose_name='Содержание раздела'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Наименование проекта'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(null=True, upload_to='media/project/', verbose_name='Файл изображения'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='order',
            field=models.PositiveIntegerField(default=2, verbose_name='Порядок отображения на сайте'),
        ),
        migrations.AlterField(
            model_name='replyfield',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='replyfield',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='replyfield',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='replyfield',
            name='request_box',
            field=models.TextField(max_length=500, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='replyfield',
            name='second_name',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок блога')),
                ('content', models.TextField(verbose_name='Содержание блога')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время изменения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/blog/image/', verbose_name='Файл изображения')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/blog/video/', verbose_name='Файл видео')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('likes', models.ManyToManyField(blank=True, related_name='blog_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'МОЙ БЛОГ',
                'verbose_name_plural': 'МОЙ БЛОГ',
            },
        ),
    ]
