# Generated by Django 4.2.16 on 2024-11-29 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_site_app', '0008_blogimage_alter_about_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogImage',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
    ]
